import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import '@/shared/config/globals.css'

import { Sidebar } from '@/widgets/sidebar'
import { Providers } from '@/shared/config/providers'

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const eudoxus = localFont({
  src: '../shared/assets/fonts/EudoxusSans-Bold.ttf',
  variable: '--font-eudoxus',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        <Providers>
          <div className='flex h-full items-stretch'>
            <Sidebar />
            <div className='flex h-screen w-full items-center justify-center'>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
